ChainNodeNet:

  Users:
    User00:
      Name: Rasmus
      PublicKey: b3883353d54d8f90832b90d5b0d23493a075942142a1ada4be675ffd954548cf
      Gateway: 
        - ChainNode01
        - ChainNode02
      Roles:
        - admin
        - contractinvoker
        - userinvoker
        - nodeinvoker
        - policyinvoker

  ChainNode01:
    Name: Org01

    Ports:
      #Listening ports
      CLI: 3401
      DLT: 3402

    DB: Block01

  ChainNode02:
    Name: Org02

    Ports:
      #Listening ports
      CLI: 3411
      DLT: 3412

    DB: Block02

  ChainNode03:
    Name: Org03

    Ports:
      #Listening ports
      CLI: 3421
      DLT: 3422

    DB: Block03

  ChainNode04:
    Name: Org04

    Ports:
      #Listening ports
      CLI: 3431
      DLT: 3432

    DB: Block04
